name: pr-lint2

on:
  pull_request:
    branches: [develop]
    paths:
      - "**.py"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install isort
          python -m pip install black
          python -m pip install flake8

      - name: Get Changed Files
        id: get_changed_files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Echo Changed Files
        run: |
          echo Changed Files: ${{ steps.get_changed_files.outputs.files }}

      - name: Run isort
        run: |
          isort ${{ steps.get_changed_files.outputs.files }} --check-only

      - name: Run black
        run: |
          black --check --diff ${{ steps.get_changed_files.outputs.files }}

      - name: Run flake8
        run: |
          flake8 ${{ steps.get_changed_files.outputs.files }}

